# __manifest__.py
{
    'name': 'Claim Management',
    'version': '17.0',
    'summary': 'Claim Management',
    'sequence': 1,
    'description': 'Manage Claim ',
    'category': 'Management',
    'author': 'Sismatix',
    'website': 'http://sismatix.co',
    'depends': ['contacts','base','purchase'],
    'data': [
        'security/ir.model.access.csv',
        'security/claim_security.xml',
        'data/claim_manage_data.xml',
        'views/menu_views.xml',
        'views/md_claim_views.xml',    
        'views/claim_type_views.xml',    
        'views/resoluation_claim_type_views.xml',    
        'views/purchase_create_claim_view.xml',    
        'views/invoice_create_claim_view.xml',  
        'views/crm_create_claim_views.xml',  
        'reports/report_claim.xml',  
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}